### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by teesloane** [teesloane/reeds#1]
User Stores:

**0.1** 
- [ ] A user can add an RSS feed to Reeds.
- [ ] A user can scan the latest news of all their feeds.
- [ ] A user can remove a feed they no longer want.
